name: Hello World

on:
  workflow_dispatch:
    inputs:
      cluster: 
        description: 'Select clusterto build'
        default: cl48
        required: true
        type: choice
        options: [cl46, cl48, cl51, c155]
      brand:
        description: 'Select brand'
        default: 'audi'
        required: true
        type: choice
        options: [audi, bently, porsche]
        
jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - name: First message
        run: |
          echo "Hello from an inline bash script in a GitHub Action Workflow!"
          echo "No errors occurred" >&2  # Prevent empty Error block

  say-hello-inline-bash1:
    runs-on: ubuntu-24.04
    steps:
      - name: Second Message
        run: |
          echo "Hello Sukanya!"
          echo "No errors occurred" >&2  # Prevent empty Error block
