name: Hello World

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - name: First message
      - run: echo ""Hello from an inline bash script in a GitHub Action Workflow!""
  say-hello-inline-bash1:
    runs-on: ubuntu-24.04
    steps:
      - name: Second Message
      - run: echo "Hello Sukanya!"
